---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	recommend_llm(recommend_llm)
	recommend_tools(recommend_tools)
	recommend_finalize(recommend_finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> recommend_llm;
	recommend_llm -. &nbsp;__end__&nbsp; .-> recommend_finalize;
	recommend_llm -. &nbsp;tools&nbsp; .-> recommend_tools;
	recommend_tools --> recommend_llm;
	recommend_finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
