CUDA_VISIBLE_DEVICES=4 PYTORCH_ALLOC_CONF=expandable_segments:True FORCE_TORCHRUN=0 llamafactory-cli train \
    --stage sft \
    --do_train True \
    --model_name_or_path /mnt/nas/szm/model/models--deepseek-ai--DeepSeek-R1-Distill-Qwen-14B \
    --preprocessing_num_workers 8 \
    --finetuning_type lora \
    --template qwen \
    --dataset house_agent \
    --output_dir /mnt/nas/szm/model/house_agent_lora_output \
    --overwrite_output_dir \
    --cutoff_len 384 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --learning_rate 2e-4 \
    --num_train_epochs 5.0 \
    --lora_target all \
    --quantization_bit 4 \
    --gradient_checkpointing True \
    --bf16 True